const fetch = require("node-fetch");
const cheerio = require("cheerio");

const url = "https://wikiwiki.jp/aigiszuki/%E7%B5%8C%E9%A8%93%E5%80%A4";

async function main() {
  const html = await (await fetch(url)).text();
  const $ = cheerio.load(html);
  const rarity = ["iron", "bronze", "silver", "gold", "platinum", "black"];
  const levels = Object.fromEntries(rarity.map(r => [r, []]));
  
  $("[id^=rgn_content1] > div > table > tbody > tr").each((i, tr) => {
    const tds = $(tr).children();
    const firstText = tds.first().text();
    if (/lv/i.test(firstText)) {
      return;
    }
    tds.map((i, td) => $(td).text())
      .get()
      .filter(t => !/\(.+\)/.test(t) && t !== firstText)
      .forEach((n, i) => {
        n = Number(n) || 0;
        if (n || !levels[rarity[i]].length) {
          levels[rarity[i]].push(n);
        }
      });
  });
  console.log("// this file is generated by build-rarity.js");
  console.log(`export default ${JSON.stringify(levels, null, 2)};`);
}

main().catch(console.error);